name: bookly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3+1
  path: ^1.8.3
  path_provider: ^2.1.2

  # Network
  http: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.8
  firebase_performance: ^0.11.1+4
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/book.json

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "images/icon.png"
  windows:
    generate: true
    image_path: "images/icon.png"
  image_path: "images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/icon.png"
